language: node_js
node_js:
- 8.9.2
notifications:
  email:
    on_success: never
    on_failure: always
script:
- npm test
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: ks/ZBlIN+JXRF4o+wACml9JlOej+DMEC0ENAimWlOLBSrIy6l5fviV4+ObIRuWMTmv+yHIEzs0UdnC8uY8BqxB163ELYnxdYton77hf2bk+Ic5NyEPUJ8CXCe7Wo1R5se/PHGmwa3CXbl2JRO81vzgCsVnVgZWXVN73VSmulpOoNSsWooZTyK3ASGt644rOUs9CYGh+x2nwYULy23lDa+BTA+/jKpkKgg9K/Jw5zZ3uh1U1z30/T4KHgbGH5p0zdhwF0O519m9ED43XDgOnO1/D+rgX/hcgcU9LdQyNMCeWS3ZxRPT8zWr1DPIPNRh5YB4bA3QjbJ5Q+RoWWgRgOos7fPs5H0MTxRq/tQ3UzLUO/2Uw7HJqO9WjN9tbBZLljJ8dkDyefkKJ242WUWrID+cS8XE9FnuY6CP8IgEVN8QtGS0EmsbWvYzOyGur4ZkTxjlX7WbJL+ZB/RBGKD/FvBQqac+MZyBwd8HlnabjP+F0YnxvESK61vZLXWtGCub6PQjwxxOeaK4AH4eC5NQ4BuHnriWWys5kRtx7OteaWhEvDXsVtl/EJRHM9TNHXEDoHeAMA7GlM0pDDQQbnzcAaOL4MJbrNrU1Xu4mi+8Ed86iODqkXC9uA36fNL7GBxQRo2Lfwhs4rdAtrTN5UlZfKf+TvpfI/NrhQHnKv2Oq/Qzw=
  on:
    tags: true
    repo: coveooss/exponential-backoff
